from __future__ import annotations
import os, re, uuid, time, subprocess, shutil, json, tempfile, requests
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional, Any
from enum import Enum
import threading
import logging
import yt_dlp

from fastapi import FastAPI, HTTPException, Request, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

# External APIs
from groq import Groq
from supabase import create_client, Client

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("backend_core")

app = FastAPI(title="Clipz-Stream Backend (Groq + Supabase Architecture)")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

# ── Storage Configuration ──────────────────────────────────────────────────
RAW_UPLOADS_DIR = "raw_uploads"
CLIPS_DIR = "clips"
os.makedirs(RAW_UPLOADS_DIR, exist_ok=True)
os.makedirs(CLIPS_DIR, exist_ok=True)

# Supabase Initialization
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY) if SUPABASE_URL and SUPABASE_KEY else None

def cleanup_expired_files(directories: List[str], max_age_seconds: float = 1800):
    now = time.time()
    for directory in directories:
        if not os.path.exists(directory): continue
        for fname in os.listdir(directory):
            fpath = os.path.join(directory, fname)
            try:
                if os.path.isfile(fpath) and (now - os.path.getmtime(fpath)) > max_age_seconds:
                    os.remove(fpath)
            except Exception as e:
                logger.warning(f"Failed to delete {fpath}: {e}")

def worker_loop(directories, max_age, interval):
    while True:
        cleanup_expired_files(directories, max_age)
        time.sleep(interval)

@app.on_event("startup")
async def startup_event():
    threading.Thread(target=worker_loop, args=([CLIPS_DIR, RAW_UPLOADS_DIR], 1800, 300), daemon=True).start()
    if not supabase:
        logger.warning("Supabase credentials not found. Clips will be served locally instead of CDN.")

# ============================================================================
# TIER 1: INGESTION & STORAGE LAYER
# ============================================================================
class ProcessRequest(BaseModel):
    url: str
    num_clips: int = 3

class IngestionBlockedError(Exception):
    """Raised when YouTube refuses the download (bot check / login wall / geo-block)."""
    pass


DEFAULT_YOUTUBE_COOKIES = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp. Do not edit.

.youtube.com\tTRUE\t/\tFALSE\t0\tPREF\tf6=40000000&hl=en&tz=UTC
.youtube.com\tTRUE\t/\tTRUE\t0\tSOCS\tCAI
"""


def _cookiefile_path():
    """
    Resolve a cookies.txt for yt-dlp so requests look like a logged-in browser
    instead of a bare datacenter IP (this is the #1 fix for 'Sign in to confirm
    you're not a bot').
    """
    path_env = os.getenv("YTDLP_COOKIES_FILE")
    if path_env and os.path.exists(path_env):
        return path_env

    content_env = os.getenv("YTDLP_COOKIES_CONTENT", DEFAULT_YOUTUBE_COOKIES)
    if content_env:
        tmp_dir = tempfile.gettempdir() if hasattr(tempfile, "gettempdir") else "/tmp"
        tmp_path = os.path.join(tmp_dir, "yt_cookies.txt")
        try:
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.write(content_env)
            return tmp_path
        except Exception as e:
            logger.warning(f"Could not materialize YTDLP_COOKIES_CONTENT: {e}")
    return None


def download_video_ingest(url: str, out_dir: str) -> str:
    out_file = os.path.join(out_dir, f"video_{uuid.uuid4().hex[:8]}.mp4")
    cookiefile = _cookiefile_path()
    proxy = os.getenv("YTDLP_PROXY")  # e.g. residential/rotating proxy URL, optional but strongly recommended
    po_token = os.getenv("YTDLP_PO_TOKEN")  # optional, see README for how to mint one

    # Client fallback order tuned for current YouTube bot-checks:
    # - tv_embedded & android bypass YouTube captcha challenges on datacenter IPs
    clients_attempts = [
        ['tv_embedded'],
        ['web_embedded'],
        ['android_embedded'],
        ['mweb'],
        ['android'],
    ]

    last_error = None
    bot_check_hit = False

    for attempt, client_list in enumerate(clients_attempts):
        yt_args = {'po_token': [po_token]} if po_token else {}
        if client_list:
            yt_args['player_client'] = client_list

        ydl_opts = {
            'format': 'b/best',
            'merge_output_format': 'mp4',
            'final_ext': 'mp4',
            'outtmpl': out_file,
            'quiet': True,
            'no_warnings': True,
            'retries': 2,
            'socket_timeout': 10,
            'extractor_args': {
                'youtube': yt_args
            },
        }
        if cookiefile:
            ydl_opts['cookiefile'] = cookiefile
        if proxy:
            ydl_opts['proxy'] = proxy

        try:
            logger.info(f"Downloading YouTube video via yt_dlp (attempt {attempt+1}/{len(clients_attempts)}, "
                        f"clients={client_list}, cookies={'yes' if cookiefile else 'no'}, proxy={'yes' if proxy else 'no'}): {url}")
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
            if os.path.exists(out_file) and os.path.getsize(out_file) > 100_000:
                return out_file
        except Exception as e:
            msg = str(e)
            last_error = msg
            if "Sign in to confirm" in msg or "not a bot" in msg or "cookies" in msg.lower():
                bot_check_hit = True
            logger.warning(f"Client list {client_list} failed: {msg}")
            time.sleep(1.5 * (attempt + 1))  # brief backoff before trying the next client persona

    # Fallback: Parse youtube.com/watch?v= directly for googlevideo stream URL
    try:
        vid_match = re.search(r'(?:v=|\/)([0-9A-Za-z_-]{11})', url)
        if vid_match:
            v_id = vid_match.group(1)
            page_url = f"https://www.youtube.com/watch?v={v_id}"
            headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
            req = requests.get(page_url, headers=headers, timeout=12)
            if req.status_code == 200:
                gv_matches = re.findall(r'https://[a-zA-Z0-9.-]+\.googlevideo\.com/videoplayback\?[^"\'\s\\]+', req.text)
                for gv_u in gv_matches:
                    u_clean = gv_u.replace("\\u0026", "&").replace("\\/", "/")
                    logger.info(f"Downloading stream directly via googlevideo parse: {u_clean[:80]}...")
                    stream_resp = requests.get(u_clean, headers=headers, stream=True, timeout=30)
                    if stream_resp.status_code == 200:
                        with open(out_file, "wb") as f_out:
                            for chunk in stream_resp.iter_content(chunk_size=1024*1024):
                                if chunk: f_out.write(chunk)
                        if os.path.exists(out_file) and os.path.getsize(out_file) > 100_000:
                            return out_file
    except Exception as fallback_e:
        logger.warning(f"Direct stream extraction fallback failed: {fallback_e}")

    raise Exception(f"Ingestion failed for {url}: {last_error if last_error else 'Stream unavailable'}. Please try another link or upload a local file.")

# ============================================================================
# TIER 2: AI PROCESSING ENGINE (GROQ)
# ============================================================================
class Hook(str, Enum):
    SECRET = "Secret"; REVELATION = "Revelation"; MONEY = "Money"; WARNING = "Warning"
    CURIOSITY = "Curiosity"; STORY = "Story"; TUTORIAL = "Tutorial"; CONTRARIAN = "Contrarian"
    EMOTIONAL = "Emotional"; RETENTION = "Retention"; GENERAL = "General"

@dataclass
class Chunk:
    start: float; end: float; text: str; words: List[dict]; score: int = 0
    hook: str = "General"; reasons: List[str] = field(default_factory=list); viable: bool = False
    @property
    def duration(self): return self.end - self.start
    def title(self) -> str:
        raw = " ".join(w["word"] for w in self.words[:6])
        return re.sub(r"[^\w\s]", "", raw).strip().capitalize()

def transcribe(video_path: str) -> List[dict]:
    # 1. Extract audio
    audio_path = video_path + ".mp3"
    subprocess.run(["ffmpeg", "-y", "-i", video_path, "-vn", "-c:a", "libmp3lame", "-q:a", "5", audio_path], check=True, capture_output=True)
    
    # 2. Call Groq with native word-level timestamps
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    with open(audio_path, "rb") as f:
        resp = client.audio.transcriptions.create(
            file=("audio.mp3", f),
            model="whisper-large-v3",
            response_format="verbose_json",
            timestamp_granularities=["word"]
        )
    if os.path.exists(audio_path):
        os.remove(audio_path)
    
    # 3. Parse word-level timestamps directly from Groq if available
    out = []
    data = resp.model_dump() if hasattr(resp, "model_dump") else (resp if isinstance(resp, dict) else {})
    
    top_words = data.get("words", [])
    if top_words:
        for w in top_words:
            w_text = w.get("word", "").strip()
            if w_text:
                out.append({
                    "word": w_text,
                    "startMs": int(w.get("start", 0.0) * 1000),
                    "endMs": int(w.get("end", 0.0) * 1000)
                })
    else:
        for seg in data.get("segments", []):
            seg_words = seg.get("words", [])
            if seg_words:
                for w in seg_words:
                    w_text = w.get("word", "").strip()
                    if w_text:
                        out.append({
                            "word": w_text,
                            "startMs": int(w.get("start", 0.0) * 1000),
                            "endMs": int(w.get("end", 0.0) * 1000)
                        })
            else:
                # Fallback to even split if no word array returned
                text = seg.get("text", "").strip()
                start = seg.get("start", 0.0)
                end = seg.get("end", 0.0)
                words = text.split()
                if not words: continue
                duration_per_word = (end - start) / len(words)
                for i, w in enumerate(words):
                    w_start = start + (i * duration_per_word)
                    w_end = w_start + duration_per_word
                    out.append({"word": w, "startMs": int(w_start * 1000), "endMs": int(w_end * 1000)})
    return out

def semantic_chunks(words: List[dict], max_gap_ms: int = 1800, min_words: int = 10, max_dur_ms: int = 90_000) -> List[Chunk]:
    if not words: return []
    SHIFTS = {"however","but","moving on","next","now","speaking of","anyway","alright","so anyway"}
    chunks: List[Chunk] = []; buf: List[dict] = []; c_start = words[0]["startMs"]; last_end = words[0]["endMs"]
    def flush():
        if len(buf) >= min_words:
            chunks.append(Chunk(start=buf[0]["startMs"]/1000, end=buf[-1]["endMs"]/1000, text=" ".join(w["word"] for w in buf), words=list(buf)))
    for w in words:
        gap = w["startMs"] - last_end; dur = w["startMs"] - c_start; wl = w["word"].lower().strip(".,!?")
        if ((gap > max_gap_ms or (len(buf) > 6 and buf[-1]["word"].endswith((".", "!", "?"))) or wl in SHIFTS or dur > max_dur_ms) and len(buf) >= min_words):
            flush(); buf = [w]; c_start = w["startMs"]
        else: buf.append(w)
        last_end = w["endMs"]
    flush()
    return chunks

def score(c: Chunk) -> Chunk:
    tl = c.text.lower(); dur = c.duration; pts = 70; reasons = ["High-retention speech hook"]; hook = Hook.GENERAL
    if not (10 <= dur <= 90):
        c.score = 0; c.viable = False; return c
    
    T1 = [(r"nobody (talks about|tells you)", Hook.SECRET, 25), (r"the (real|hidden) truth", Hook.REVELATION, 23)]
    for pat, h, p in T1:
        if re.search(pat, tl): pts += p; hook = h; reasons.append(f"Strong hook — {h.value}"); break
        
    c.score = min(99, max(50, pts)); c.hook = hook.value; c.reasons = reasons; c.viable = True
    return c

def select(scored: List[Chunk], n: int) -> List[Chunk]:
    pool = sorted([c for c in scored if c.viable], key=lambda x: -x.score)
    if not pool: pool = sorted(scored, key=lambda x: -x.score)
    sel: List[Chunk] = []; used: List[tuple] = []
    for c in pool:
        if len(sel) >= n: break
        # Smart Deduplication: ensure minimum 5.0 second gap between clips
        if any(not (c.end + 5.0 < s or c.start - 5.0 > e) for s, e in used): continue
        sel.append(c); used.append((c.start, c.end))
    sel.sort(key=lambda x: x.start)
    return sel

def generate_ass_file(words: List[dict], clip_start_sec: float, ass_out_path: str):
    """Generates an ASS subtitle file with kinetic word highlighting and bold stroke outline"""
    header = """[Script Info]
ScriptType: v4.00+
PlayResX: 720
PlayResY: 1280

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,36,&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,4,0,2,20,20,160,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    lines_events = []
    group = []
    clip_words = [w for w in words if (w.get("startMs", 0)/1000.0) >= clip_start_sec - 0.5]
    
    for i, w in enumerate(clip_words):
        group.append(w)
        if len(group) >= 4 or i == len(clip_words) - 1:
            line_start_sec = max(0, (group[0]["startMs"] / 1000.0) - clip_start_sec)
            line_end_sec = max(line_start_sec + 0.4, (group[-1]["endMs"] / 1000.0) - clip_start_sec)
            
            def format_time(sec):
                hrs = int(sec // 3600)
                mins = int((sec % 3600) // 60)
                secs = int(sec % 60)
                cs = int((sec % 1) * 100)
                return f"{hrs}:{mins:02d}:{secs:02d}.{cs:02d}"
            
            start_str = format_time(line_start_sec)
            end_str = format_time(line_end_sec)
            line_text = " ".join(str(w.get("word", "")).upper() for w in group)
            event_line = f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{{\\c&H0000FFFF&}}{line_text}"
            lines_events.append(event_line)
            group = []
            
    with open(ass_out_path, "w", encoding="utf-8") as f:
        f.write(header + "\n".join(lines_events))

# ============================================================================
# TIER 3: DELIVERY LAYER (FFmpeg OpenCV Face-Tracking Crop & Supabase)
# ============================================================================
def analyze_face_centers(vpath: str, start_sec: float, end_sec: float, sample_fps: float = 2.0) -> list:
    """Sample video frames between start_sec and end_sec, detect faces with OpenCV Haar Cascade, return [(t_rel, norm_x)]"""
    try:
        import cv2
        if not os.path.exists(vpath): return []
        cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        if not os.path.exists(cascade_path): return []
        
        face_cascade = cv2.CascadeClassifier(cascade_path)
        cap = cv2.VideoCapture(vpath)
        if not cap.isOpened(): return []
        
        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        width = cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 1920.0
        
        start_frame = int(start_sec * fps)
        end_frame = int(end_sec * fps)
        frame_step = max(1, int(fps / sample_fps))
        
        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)
        current_frame = start_frame
        points = []
        
        while current_frame <= end_frame:
            ret, frame = cap.read()
            if not ret: break
            t_rel = (current_frame - start_frame) / fps
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, minSize=(60, 60))
            if len(faces) > 0:
                largest_face = max(faces, key=lambda rect: rect[2] * rect[3])
                x, y, w, h = largest_face
                center_x_norm = (x + w / 2.0) / width
                points.append((t_rel, center_x_norm))
            current_frame += frame_step
            cap.set(cv2.CAP_PROP_POS_FRAMES, current_frame)
        cap.release()
        return points
    except Exception as e:
        logger.warning(f"OpenCV face tracking error: {e}")
        return []

def build_dynamic_crop_x_expr(points: List[Tuple[float, float]]) -> str:
    """Build dynamic FFmpeg linear interpolation crop x expression from face points"""
    if not points: return "(in_w-out_w)/2"
    smoothed = []
    curr_bin = None
    bin_vals = []
    for t, x_norm in points:
        t_sec = int(t)
        if curr_bin is None: curr_bin = t_sec
        if t_sec == curr_bin:
            bin_vals.append(x_norm)
        else:
            smoothed.append((curr_bin, sum(bin_vals) / len(bin_vals)))
            curr_bin = t_sec
            bin_vals = [x_norm]
    if bin_vals and curr_bin is not None:
        smoothed.append((curr_bin, sum(bin_vals) / len(bin_vals)))
    if not smoothed: return "(in_w-out_w)/2"
    
    expr_parts = []
    for t_sec, norm_x in smoothed:
        target_x = f"min(max(0,in_w*{norm_x:.3f}-out_w/2),in_w-out_w)"
        expr_parts.append(f"gte(t,{t_sec:.1f}),{target_x}")
        
    expr = "(in_w-out_w)/2"
    for part in reversed(expr_parts):
        cond, val = part.split(",", 1)
        expr = f"if({cond},{val},{expr})"
    return expr

def transcode_and_upload(src: str, start: float, end: float, out: str, words: List[dict] = None) -> str:
    """Safe FFmpeg crop + OpenCV Face-Tracking + ASS Kinetic Subtitles + Supabase CDN Upload"""
    dur = end - start
    
    # 1. Analyze face positions for dynamic 9:16 speaker tracking
    face_pts = analyze_face_centers(src, start, end)
    crop_x_expr = build_dynamic_crop_x_expr(face_pts)
    logger.info(f"OpenCV Face Tracking generated {len(face_pts)} face samples. Crop X expr: {crop_x_expr[:60]}...")
    
    # 2. Generate ASS Subtitle File if words provided
    ass_path = out + ".ass"
    use_subtitles = False
    if words:
        try:
            generate_ass_file(words, start, ass_path)
            use_subtitles = os.path.exists(ass_path)
        except Exception as e:
            logger.warning(f"ASS subtitle generation failed: {e}")
            
    crop_filter = f"scale=ih*9/16:ih:force_original_aspect_ratio=increase,crop=w=ih*9/16:h=ih:x='{crop_x_expr}':y=0,scale=720:1280"
    if use_subtitles:
        escaped_ass = ass_path.replace("\\", "/").replace(":", "\\:")
        vf = f"{crop_filter},subtitles='{escaped_ass}',fps=30"
    else:
        vf = f"{crop_filter},fps=30"
        
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-ss", str(max(0.0, start - 1.5)), "-i", src, "-ss", str(min(1.5, start)), "-t", str(dur),
        "-vf", vf, "-c:v", "libx264", "-preset", "ultrafast", "-crf", "26",
        "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", "-pix_fmt", "yuv420p", out
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        logger.error(f"FFmpeg transcoding failed (exit code {res.returncode}): {res.stderr}")
        raise Exception(f"FFmpeg transcode failed: {res.stderr[-300:] if res.stderr else 'Unknown error'}")
    if os.path.exists(ass_path):
        try: os.remove(ass_path)
        except: pass

    # Upload to Supabase Storage
    if supabase:
        fname = os.path.basename(out)
        with open(out, 'rb') as f:
            res = supabase.storage.from_("clips").upload(path=fname, file=f, file_options={"content-type": "video/mp4"})
            logger.info(f"Supabase upload response: {res}")
        public_url = supabase.storage.from_("clips").get_public_url(fname)
        return public_url
    else:
        return f"/clips/{os.path.basename(out)}"

def llama_analyze_chunks(chunks: List[Chunk], n: int) -> List[dict]:
    """Call Groq Llama-3-70B to score clips, write viral titles & identify hooks"""
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    
    payload_chunks = []
    for idx, c in enumerate(chunks):
        payload_chunks.append({
            "id": idx,
            "start": round(c.start, 1),
            "end": round(c.end, 1),
            "duration": round(c.duration, 1),
            "text": c.text
        })
        
    prompt = f"""
You are an elite viral video editor for TikTok, Instagram Reels, and YouTube Shorts (like Opus Clip & Wayin).
Analyze the following transcript chunks from a video and select the top {n} most engaging, high-retention segments.

TRANSCRIPT CHUNKS:
{json.dumps(payload_chunks, indent=2)}

Return ONLY a JSON object with key "clips". Each clip must have:
- "chunk_id": int (the id of the selected chunk)
- "title": str (catchy headline with emoji, max 6 words)
- "viralScore": int (82 to 99)
- "hookType": str (one of: Secret, Revelation, Story, Contrarian, Tutorial, Curiosity, Emotional, Warning)
- "viralReason": str (1 crisp sentence explaining why this clip will perform well)
"""
    try:
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        data = json.loads(resp.choices[0].message.content)
        return data.get("clips", [])
    except Exception as e:
        logger.error(f"Groq Llama-3 70B analysis error: {e}")
        return []

# ── Persistent Job Tracking ────────────────────────────────────────────────
JOBS = {}
modal_background_job_fn = None

def push_job_update(job_id: str, progress: int, current_step: str, status: str = None, result: dict = None, error: str = None):
    data = {
        "job_id": job_id,
        "progress": progress,
        "current_step": current_step
    }
    if status: data["status"] = status
    if result: data["result"] = result
    if error: data["error"] = error

    if job_id:
        if job_id not in JOBS:
            JOBS[job_id] = {"job_id": job_id, "status": "processing", "progress": 0, "current_step": "", "result": None, "error": None}
        JOBS[job_id].update(data)

    if supabase and job_id:
        try:
            supabase.table("jobs").upsert(data).execute()
        except Exception as e:
            logger.warning(f"Failed to persist job status in Supabase Postgres ({job_id}): {e}")

async def run_pipeline(vpath: str, url_or_name: str, n: int, base: str, job_id: str = None) -> dict:
    def update_job(prog: int, step: str):
        if job_id:
            push_job_update(job_id, prog, step)

    update_job(10, "Extracting audio & Groq WhisperX transcription...")
    logger.info("Starting Groq Whisper AI Engine analysis...")
    words = transcribe(vpath)
    if not words: raise HTTPException(500, "No speech detected in video")
    
    update_job(35, "Groq Llama-3-70B Viral Hook & Retention Analysis...")
    chunks = semantic_chunks(words)
    if not chunks: raise HTTPException(500, "Could not form speech segments")

    # Call Llama-3 70B AI Engine
    llama_analysis = llama_analyze_chunks(chunks, n)
    
    chosen_chunks = []
    if llama_analysis:
        for la in llama_analysis:
            cid = la.get("chunk_id", 0)
            if 0 <= cid < len(chunks):
                c = chunks[cid]
                c.score = la.get("viralScore", 85)
                c.hook = la.get("hookType", "General")
                c.reasons = [la.get("viralReason", "High-engagement viral hook")]
                c.text = la.get("title", c.title()) # Override title
                chosen_chunks.append((c, la.get("title", c.title())))
    
    if not chosen_chunks:
        scored = [score(c) for c in chunks]
        chosen = select(scored, n)
        chosen_chunks = [(c, c.title()) for c in chosen]

    update_job(60, "FFmpeg 9:16 Safe Crop & Supabase CDN Transcoding...")
    logger.info("Transcoding and uploading clips in parallel...")
    clips_out = [None] * len(chosen_chunks)

    import concurrent.futures

    def process_single_chunk(index_and_tuple):
        i, (chunk, title_text) = index_and_tuple
        fname = f"clip_{uuid.uuid4().hex[:8]}_{i}.mp4"
        fpath = os.path.join(CLIPS_DIR, fname)
        try:
            clip_url = transcode_and_upload(vpath, chunk.start, chunk.end, fpath, words=chunk.words)
            if clip_url.startswith("/clips/"):
                clip_url = f"{base}{clip_url}"
                
            off = chunk.words[0]["startMs"]
            captions = [{"word": w["word"], "startMs": w["startMs"] - off, "endMs": w["endMs"] - off} for w in chunk.words]
            t_clean = title_text if title_text.startswith("🔥") or title_text.startswith("⚡") else f"🔥 {title_text}"
            return i, {
                "title": t_clean, "startSec": int(chunk.start), "endSec": int(chunk.end),
                "viralScore": chunk.score, "viralReason": chunk.reasons[0] if chunk.reasons else "High-engagement clip",
                "captions": captions, "clipUrl": clip_url, "clip_url": clip_url,
                "hookType": chunk.hook, "allReasons": chunk.reasons, "durationSec": round(chunk.duration, 1),
            }
        except Exception as e:
            logger.error(f"Failed to transcode chunk {i}: {e}")
            return i, None

    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, len(chosen_chunks))) as executor:
        futures = [executor.submit(process_single_chunk, (i, chunk_tuple)) for i, chunk_tuple in enumerate(chosen_chunks)]
        for future in concurrent.futures.as_completed(futures):
            idx, res_data = future.result()
            if res_data:
                clips_out[idx] = res_data

    clips_out = [c for c in clips_out if c is not None]

    result = {"url": url_or_name, "duration": words[-1]["endMs"]/1000 if words else 0, "clips": clips_out}
    logger.info(f"Pipeline completed successfully. Generated {len(clips_out)} viable clips.")
    update_job(100, "Complete")
    return result

def execute_job_bg(job_id: str, vpath: str, url_or_name: str, n: int, base: str):
    try:
        import asyncio
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        res = loop.run_until_complete(run_pipeline(vpath, url_or_name, n, base, job_id))
        push_job_update(job_id, progress=100, current_step="Complete", status="completed", result=res)
    except Exception as e:
        logger.error(f"Job {job_id} failed: {e}")
        push_job_update(job_id, progress=0, current_step="Failed", status="failed", error=str(e))

@app.post("/api/process")
async def process_video_api(body: ProcessRequest, request: Request):
    if not body.url.strip(): raise HTTPException(400, "URL cannot be empty")
    base = str(request.base_url).rstrip("/")
    try:
        vpath = download_video_ingest(body.url.strip(), RAW_UPLOADS_DIR)
        return await run_pipeline(vpath, body.url.strip(), max(1, min(body.num_clips, 8)), base)
    except Exception as e:
        logger.error(f"Process failed: {e}")
        raise HTTPException(500, str(e))

@app.post("/api/jobs/create")
async def create_job_api(body: ProcessRequest, request: Request):
    if not body.url.strip(): raise HTTPException(400, "URL cannot be empty")
    base = str(request.base_url).rstrip("/")
    job_id = uuid.uuid4().hex[:12]
    
    push_job_update(
        job_id=job_id,
        progress=2,
        current_step="Ingesting video & validating media streams...",
        status="processing"
    )
    
    num_c = max(1, min(body.num_clips, 8))
    if modal_background_job_fn is not None:
        logger.info(f"Spawning native Modal background container for job {job_id}")
        modal_background_job_fn.spawn(job_id, body.url.strip(), num_c, base)
    else:
        def worker():
            try:
                vpath = download_video_ingest(body.url.strip(), RAW_UPLOADS_DIR)
                execute_job_bg(job_id, vpath, body.url.strip(), num_c, base)
            except Exception as e:
                logger.error(f"Job {job_id} ingestion failed: {e}")
                push_job_update(job_id, progress=0, current_step="Failed", status="failed", error=str(e))

        threading.Thread(target=worker, daemon=True).start()
        
    return {"job_id": job_id, "status": "processing"}

@app.get("/api/jobs/status/{job_id}")
async def get_job_status(job_id: str):
    if supabase:
        try:
            res = supabase.table("jobs").select("*").eq("job_id", job_id).execute()
            if res.data and len(res.data) > 0:
                return res.data[0]
        except Exception as e:
            logger.warning(f"Failed to fetch job status from Supabase DB ({job_id}): {e}")

    if job_id in JOBS:
        return JOBS[job_id]

    raise HTTPException(404, "Job not found")

@app.post("/api/upload")
async def upload_video_api(request: Request, file: UploadFile = File(...), num_clips: int = Form(3)):
    base = str(request.base_url).rstrip("/")
    ext = os.path.splitext(file.filename)[1] or ".mp4"
    vpath = os.path.join(RAW_UPLOADS_DIR, f"uploaded_{uuid.uuid4().hex[:8]}{ext}")
    try:
        with open(vpath, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        return await run_pipeline(vpath, file.filename, max(1, min(num_clips, 8)), base)
    except Exception as e:
        logger.error(f"Upload failed: {e}")
        raise HTTPException(500, str(e))

@app.get("/clips/{filename}")
async def serve_clip(filename: str):
    path = os.path.join(CLIPS_DIR, filename)
    if not os.path.exists(path):
        raise HTTPException(404, "Clip not found")
    return FileResponse(path, media_type="video/mp4")

@app.get("/health")
def health():
    return {"status": "ok", "architecture": "Groq Llama-3-70B + Supabase Serverless"}

@app.get("/")
def root():
    return {"api": "POST /api/process, POST /api/jobs/create, GET /api/jobs/status/{job_id}", "health": "GET /health"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8000)))

# Modal Cloud Deployment Handler
try:
    import modal
    image = (
        modal.Image.debian_slim(python_version="3.11")
        .apt_install("ffmpeg")
        .pip_install("fastapi", "yt-dlp", "groq", "requests", "supabase", "python-dotenv", "python-multipart", "opencv-python-headless")
    )
    modal_app = modal.App("clipz-stream-fastapi-app")
    
    secret_dict = {}
    if os.getenv("GROQ_API_KEY"):
        secret_dict["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")
    if os.getenv("SUPABASE_URL"):
        secret_dict["SUPABASE_URL"] = os.getenv("SUPABASE_URL")
    if os.getenv("SUPABASE_KEY"):
        secret_dict["SUPABASE_KEY"] = os.getenv("SUPABASE_KEY")
    if os.getenv("YTDLP_COOKIES_CONTENT"):
        secret_dict["YTDLP_COOKIES_CONTENT"] = os.getenv("YTDLP_COOKIES_CONTENT")

    secret = modal.Secret.from_dict(secret_dict) if secret_dict else None
    secrets_list = [secret] if secret else []

    @modal_app.function(image=image, timeout=600, cpu=2.0, secrets=secrets_list)
    @modal.asgi_app()
    def fastapi_app():
        return app
except Exception:
    pass
