from __future__ import annotations
import os, re, uuid, time, subprocess, shutil, json, tempfile, requests
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional, Any
from enum import Enum
import threading
import logging
import concurrent.futures
import yt_dlp
from yt_dlp.utils import download_range_func

from fastapi import FastAPI, HTTPException, Request, File, UploadFile, Form, BackgroundTasks, Body
from fastapi.concurrency import run_in_threadpool
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

# External APIs
from groq import Groq
from supabase import create_client, Client

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("backend_core")

app = FastAPI(title="Clipz-Stream Backend (Groq + Supabase Architecture)")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

# Storage Configuration
_STORAGE_ROOT = os.getenv("CLIPZ_STORAGE_DIR")
if not _STORAGE_ROOT and os.path.exists("/root/storage"):
    _STORAGE_ROOT = "/root/storage"

RAW_UPLOADS_DIR = os.path.join(_STORAGE_ROOT, "raw_uploads") if _STORAGE_ROOT else "raw_uploads"
CLIPS_DIR = os.path.join(_STORAGE_ROOT, "clips") if _STORAGE_ROOT else "clips"
os.makedirs(RAW_UPLOADS_DIR, exist_ok=True)
os.makedirs(CLIPS_DIR, exist_ok=True)

# Supabase Initialization
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY) if SUPABASE_URL and SUPABASE_KEY else None

def cleanup_expired_files(directories: List[str], max_age_seconds: float = 1800):
    now = time.time()
    for directory in directories:
        if not os.path.exists(directory): continue
        for fname in os.listdir(directory):
            fpath = os.path.join(directory, fname)
            try:
                if os.path.isfile(fpath) and (now - os.path.getmtime(fpath)) > max_age_seconds:
                    os.remove(fpath)
            except Exception as e:
                logger.warning(f"Failed to delete {fpath}: {e}")

def resolve_media_binary(env_name: str, executable: str) -> str:
    configured = os.getenv(env_name)
    if configured:
        return configured
    return shutil.which(executable) or executable

def worker_loop(directories, max_age, interval):
    while True:
        cleanup_expired_files(directories, max_age)
        time.sleep(interval)

@app.on_event("startup")
async def startup_event():
    # Run cleanup worker: keep files for 48 hours (172800s), check every hour (3600s)
    threading.Thread(target=worker_loop, args=([CLIPS_DIR, RAW_UPLOADS_DIR], 172800, 3600), daemon=True).start()
    if not supabase:
        logger.warning("Supabase credentials not found. Clips will be served locally instead of CDN.")

# ============================================================================
# TIER 1: INGESTION & STORAGE LAYER
# ============================================================================
class ProcessRequest(BaseModel):
    url: str
    num_clips: int = 3
    burn_captions: bool = True

class RenderRequest(BaseModel):
    url: str
    clips: List[dict]

class IngestionBlockedError(Exception):
    """Raised when YouTube refuses the download (bot check / login wall / geo-block)."""
    pass


DEFAULT_YOUTUBE_COOKIES = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp. Do not edit.

.youtube.com\tTRUE\t/\tFALSE\t0\tPREF\tf6=40000000&hl=en&tz=UTC
.youtube.com\tTRUE\t/\tTRUE\t0\tSOCS\tCAI
"""


def _cookiefile_path():
    """
    Resolve a cookies.txt for yt-dlp so requests look like a logged-in browser
    instead of a bare datacenter IP (this is the #1 fix for 'Sign in to confirm
    you're not a bot').
    """
    path_env = os.getenv("YTDLP_COOKIES_FILE")
    if path_env and os.path.exists(path_env):
        return path_env

    content_env = os.getenv("YTDLP_COOKIES_CONTENT", DEFAULT_YOUTUBE_COOKIES)
    if content_env:
        tmp_dir = tempfile.gettempdir() if hasattr(tempfile, "gettempdir") else "/tmp"
        tmp_path = os.path.join(tmp_dir, "yt_cookies.txt")
        try:
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.write(content_env)
            return tmp_path
        except Exception as e:
            logger.warning(f"Could not materialize YTDLP_COOKIES_CONTENT: {e}")
    return None


class IngestionBlockedError(Exception):
    """Raised when YouTube refuses the download (bot check / login wall / geo-block)."""
    pass

def download_video_ingest(url: str, out_dir: str, job_id: str = None) -> str:
    out_file = os.path.join(out_dir, f"video_{uuid.uuid4().hex[:8]}.mp4")

    vid_match = re.search(r'(?:v=|\/)([0-9A-Za-z_-]{11})', url)
    if not vid_match:
        raise Exception("Could not parse YouTube video ID from URL")

    v_id = vid_match.group(1)

    rapidapi_key = os.getenv("RAPIDAPI_KEY")
    if not rapidapi_key:
        raise Exception("RAPIDAPI_KEY is missing from environment. Please add it to Modal Secrets.")

    headers = {
        'x-rapidapi-host': 'cloud-api-hub-youtube-downloader.p.rapidapi.com',
        'x-rapidapi-key': rapidapi_key
    }

    if job_id: push_job_update(job_id, progress=5, current_step="Connecting to high-speed ingest network...")

    api_url = f"https://cloud-api-hub-youtube-downloader.p.rapidapi.com/download?id={v_id}"
    logger.info(f"Fetching video info from API for {v_id}")
    req = requests.get(api_url, headers=headers, timeout=20)

    if req.status_code != 200 or (isinstance(req.json(), dict) and 'error' in req.json()):
        raise Exception("Failed to fetch video stream from RapidAPI. Please use 'Upload Video File' instead.")

    data = req.json()
    formats = data if isinstance(data, list) else data.get('formats', [])
    combined = [f for f in formats if str(f.get('acodec')) != 'none' and str(f.get('vcodec')) != 'none']

    if not combined:
        raise Exception("No combined audio/video streams found. Please use 'Upload Video File' instead.")

    combined.sort(key=lambda x: int(x.get('height') or 0), reverse=True)
    best_stream = combined[0]
    stream_url = best_stream.get('url')

    if not stream_url:
        raise Exception("Stream URL was empty from API.")

    if job_id: push_job_update(job_id, progress=10, current_step=f"Downloading high-resolution source video ({best_stream.get('height')}p)...")
    logger.info(f"Downloading {best_stream.get('height')}p stream...")

    stream_resp = requests.get(stream_url, stream=True, timeout=30)
    if stream_resp.status_code == 200:
        with open(out_file, "wb") as f_out:
            for chunk in stream_resp.iter_content(chunk_size=1024*1024):
                if chunk: f_out.write(chunk)
        if os.path.getsize(out_file) > 100_000:
            if job_id: push_job_update(job_id, progress=20, current_step="Video ingestion completed successfully.")
            return out_file

    raise Exception(f"Ingestion failed for {url}: Could not download media streams. Please use 'Upload Video File' instead.")

def is_youtube_url(url: str) -> bool:
    return "youtube.com" in url or "youtu.be" in url


def extract_youtube_id(url: str) -> Optional[str]:
    match = re.search(r'(?:v=|youtu\.be/|/shorts/|/embed/)([0-9A-Za-z_-]{11})', url)
    return match.group(1) if match else None


def fetch_youtube_transcript_words(url_or_id: str) -> List[dict]:
    """Fetch YouTube captions as approximate word timestamps without downloading media."""
    video_id = url_or_id if re.fullmatch(r"[0-9A-Za-z_-]{11}", url_or_id) else extract_youtube_id(url_or_id)
    if not video_id:
        return []

    try:
        from youtube_transcript_api import YouTubeTranscriptApi

        api = YouTubeTranscriptApi()
        transcript = api.fetch(video_id)
        words: List[dict] = []

        for item in transcript:
            if isinstance(item, dict):
                start = float(item.get("start", 0.0) or 0.0)
                duration = float(item.get("duration", 2.0) or 2.0)
                text = str(item.get("text", "") or "")
            else:
                start = float(getattr(item, "start", 0.0) or 0.0)
                duration = float(getattr(item, "duration", 2.0) or 2.0)
                text = str(getattr(item, "text", "") or "")

            parts = [p for p in re.split(r"\s+", text.replace("\n", " ").strip()) if p]
            if not parts:
                continue

            start_ms = int(start * 1000)
            duration_ms = max(100, int(duration * 1000))
            per_word = max(80, duration_ms // len(parts))

            for idx, word in enumerate(parts):
                word_start = start_ms + (idx * per_word)
                words.append({"word": word, "startMs": word_start, "endMs": word_start + per_word})

        return words
    except Exception as e:
        logger.warning(f"YouTubeTranscriptApi transcript fetch failed for {video_id}: {e}")
        return []


def download_youtube_section(url: str, out_dir: str, start: float, end: float, index: int, job_id: str = None) -> str:
    """Download only the selected YouTube time window to avoid full podcast downloads."""
    os.makedirs(out_dir, exist_ok=True)
    section_start = max(0.0, start)
    section_end = max(section_start + 3.0, end)
    out_file = os.path.join(out_dir, f"yt_section_{uuid.uuid4().hex[:8]}_{index}.mp4")
    cookiefile = _cookiefile_path()
    po_token = os.getenv("YTDLP_PO_TOKEN")
    proxy = os.getenv("YTDLP_PROXY")
    yt_args = {"player_client": ["android_vr", "android", "mweb"]}
    if po_token:
        yt_args["po_token"] = [po_token]

    def _section_progress_hook(d):
        if d.get("status") == "downloading" and job_id:
            total_b = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            downloaded_b = d.get("downloaded_bytes") or 0
            if total_b > 0:
                pct = int((downloaded_b / total_b) * 100)
                push_job_update(
                    job_id,
                    progress=35 + min(20, pct // 5),
                    current_step=f"Downloading selected clip window {index + 1} ({pct}%)..."
                )

    ydl_opts = {
        "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "merge_output_format": "mp4",
        "final_ext": "mp4",
        "outtmpl": out_file,
        "quiet": True,
        "no_warnings": True,
        "retries": 3,
        "socket_timeout": 20,
        "download_ranges": download_range_func(None, [(section_start, section_end)]),
        "force_keyframes_at_cuts": True,
        "progress_hooks": [_section_progress_hook],
        "extractor_args": {"youtube": yt_args},
    }
    if cookiefile:
        ydl_opts["cookiefile"] = cookiefile
    if proxy:
        ydl_opts["proxy"] = proxy

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
    except Exception as section_err:
        logger.warning(f"download_ranges failed ({section_err}), retrying full stream download fallback...")
        ydl_opts.pop("download_ranges", None)
        ydl_opts.pop("force_keyframes_at_cuts", None)
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
        except Exception as e2:
            logger.warning(f"Full stream retry failed: {e2}")

    if not os.path.exists(out_file) or os.path.getsize(out_file) < 50_000:
        logger.info("Attempting Cobalt API fallback for section download...")
        try:
            headers = {
                "Accept": "application/json",
                "Content-Type": "application/json",
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
            }
            payload = {"url": url, "vCodec": "h264", "videoQuality": "1080"}
            resp = requests.post("https://api.cobalt.tools/api/json", json=payload, headers=headers, timeout=15)
            if resp.status_code == 200:
                data = resp.json()
                dl_url = data.get("url")
                if dl_url:
                    dl_resp = requests.get(dl_url, headers={"User-Agent": headers["User-Agent"]}, stream=True, timeout=60)
                    if dl_resp.status_code == 200:
                        with open(out_file, "wb") as f_out:
                            for chunk in dl_resp.iter_content(chunk_size=1024*1024):
                                if chunk: f_out.write(chunk)
                        if os.path.exists(out_file) and os.path.getsize(out_file) > 50_000:
                            logger.info(f"Cobalt API fallback succeeded for section: {out_file}")
                            return out_file
        except Exception as ce:
            logger.warning(f"Cobalt API fallback note for section: {ce}")

        raise Exception(f"Failed to fetch video stream. YouTube has temporarily blocked our server. Please use 'Upload Video File' instead.")

    return out_file

# ============================================================================
# TIER 2: AI PROCESSING ENGINE (GROQ)
# ============================================================================
class Hook(str, Enum):
    SECRET = "Secret"; REVELATION = "Revelation"; MONEY = "Money"; WARNING = "Warning"
    CURIOSITY = "Curiosity"; STORY = "Story"; TUTORIAL = "Tutorial"; CONTRARIAN = "Contrarian"
    EMOTIONAL = "Emotional"; RETENTION = "Retention"; GENERAL = "General"

@dataclass
class Chunk:
    start: float; end: float; text: str; words: List[dict]; score: int = 0
    hook: str = "General"; reasons: List[str] = field(default_factory=list); viable: bool = False
    broll_query: str = ""
    @property
    def duration(self): return self.end - self.start
    def title(self) -> str:
        raw = " ".join(w["word"] for w in self.words[:6])
        return re.sub(r"[^\w\s]", "", raw).strip().capitalize()


def get_duration(video_path: str) -> float:
    """Return video duration in seconds using ffprobe, or 0 when probing fails."""
    try:
        res = subprocess.run(
            [
                resolve_media_binary("FFPROBE_BINARY", "ffprobe"), "-v", "error", "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1", video_path
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return float((res.stdout or "0").strip() or 0)
    except Exception as e:
        logger.warning(f"Could not probe video duration for {video_path}: {e}")
        return 0.0

def validate_rendered_mp4(path: str, expected_min_duration: float = 0.5) -> None:
    if not os.path.exists(path):
        raise Exception("Rendered MP4 was not created")
    size = os.path.getsize(path)
    if size <= 1024:
        raise Exception(f"Rendered MP4 is too small ({size} bytes)")
    with open(path, "rb") as f:
        header = f.read(32)
    if b"ftyp" not in header:
        raise Exception("Rendered file does not look like an MP4")

    ffprobe_bin = os.getenv("FFPROBE_BINARY") or shutil.which("ffprobe")
    if not ffprobe_bin:
        logger.warning("ffprobe is unavailable; using basic MP4 validation only.")
        return

    res = subprocess.run(
        [
            ffprobe_bin, "-v", "error",
            "-select_streams", "v:0",
            "-show_entries", "stream=codec_type,width,height:format=duration",
            "-of", "json", path,
        ],
        check=True,
        capture_output=True,
        text=True,
        timeout=30,
    )
    probe = json.loads(res.stdout or "{}")
    streams = probe.get("streams") or []
    if not streams:
        raise Exception("Rendered MP4 has no video stream")
    width = int(streams[0].get("width") or 0)
    height = int(streams[0].get("height") or 0)
    duration = float((probe.get("format") or {}).get("duration") or 0)
    if width <= 0 or height <= 0:
        raise Exception("Rendered MP4 has invalid dimensions")
    if duration < expected_min_duration:
        raise Exception(f"Rendered MP4 duration is invalid ({duration:.2f}s)")

def render_worker_count(requested_clips: int) -> int:
    configured = os.getenv("CLIP_RENDER_WORKERS", "2")
    try:
        workers = int(configured)
    except ValueError:
        workers = 2
    workers = max(1, min(workers, 4))
    return min(workers, max(1, requested_clips))


def build_uniform_chunks(video_path: str, max_clips: int) -> List[Chunk]:
    """Last-resort segmentation so uploads still produce downloadable clips."""
    duration = get_duration(video_path) or 60.0
    clip_count = max(1, min(max_clips, 8))
    min_len = 5.0 if duration >= clip_count * 5.0 else max(2.0, duration / clip_count)
    clip_len = min(30.0, max(min_len, duration / clip_count))
    chunks: List[Chunk] = []
    start = 0.0
    while start < duration and len(chunks) < clip_count:
        end = min(start + clip_len, duration)
        if end - start < 5.0:
            break
        label = f"Auto fallback segment {len(chunks) + 1}"
        chunks.append(
            Chunk(
                start=start,
                end=end,
                text=label,
                words=[{"word": label, "startMs": int(start * 1000), "endMs": int(end * 1000)}],
                score=max(70, 86 - (len(chunks) * 3)),
                hook="General",
                reasons=["Generated from timed fallback because transcript AI was unavailable."],
                viable=True,
            )
        )
        start = end
    return chunks
def transcribe(video_path: str) -> List[dict]:
    # 1. Extract audio
    audio_path = video_path + ".mp3"
    subprocess.run([resolve_media_binary("FFMPEG_BINARY", "ffmpeg"), "-y", "-i", video_path, "-vn", "-c:a", "libmp3lame", "-q:a", "5", audio_path], check=True, capture_output=True)

    # 2. Call Groq with native word-level timestamps
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    with open(audio_path, "rb") as f:
        resp = client.audio.transcriptions.create(
            file=("audio.mp3", f),
            model="whisper-large-v3",
            response_format="verbose_json",
            timestamp_granularities=["word"]
        )
    if os.path.exists(audio_path):
        os.remove(audio_path)

    # 3. Parse word-level timestamps directly from Groq if available
    out = []
    data = resp.model_dump() if hasattr(resp, "model_dump") else (resp if isinstance(resp, dict) else {})

    top_words = data.get("words", [])
    if top_words:
        for w in top_words:
            w_text = w.get("word", "").strip()
            if w_text:
                out.append({
                    "word": w_text,
                    "startMs": int(w.get("start", 0.0) * 1000),
                    "endMs": int(w.get("end", 0.0) * 1000)
                })
    else:
        for seg in data.get("segments", []):
            seg_words = seg.get("words", [])
            if seg_words:
                for w in seg_words:
                    w_text = w.get("word", "").strip()
                    if w_text:
                        out.append({
                            "word": w_text,
                            "startMs": int(w.get("start", 0.0) * 1000),
                            "endMs": int(w.get("end", 0.0) * 1000)
                        })
            else:
                # Fallback to even split if no word array returned
                text = seg.get("text", "").strip()
                start = seg.get("start", 0.0)
                end = seg.get("end", 0.0)
                words = text.split()
                if not words: continue
                duration_per_word = (end - start) / len(words)
                for i, w in enumerate(words):
                    w_start = start + (i * duration_per_word)
                    w_end = w_start + duration_per_word
                    out.append({"word": w, "startMs": int(w_start * 1000), "endMs": int(w_end * 1000)})
    return out

def semantic_chunks(words: List[dict], max_gap_ms: int = 1800, min_words: int = 10, max_dur_ms: int = 90_000) -> List[Chunk]:
    if not words: return []
    SHIFTS = {"however","but","moving on","next","now","speaking of","anyway","alright","so anyway"}
    chunks: List[Chunk] = []; buf: List[dict] = []; c_start = words[0]["startMs"]; last_end = words[0]["endMs"]
    def flush():
        if len(buf) >= min_words:
            chunks.append(Chunk(start=buf[0]["startMs"]/1000, end=buf[-1]["endMs"]/1000, text=" ".join(w["word"] for w in buf), words=list(buf)))
    for w in words:
        gap = w["startMs"] - last_end; dur = w["startMs"] - c_start; wl = w["word"].lower().strip(".,!?")
        if ((gap > max_gap_ms or (len(buf) > 6 and buf[-1]["word"].endswith((".", "!", "?"))) or wl in SHIFTS or dur > max_dur_ms) and len(buf) >= min_words):
            flush(); buf = [w]; c_start = w["startMs"]
        else: buf.append(w)
        last_end = w["endMs"]
    flush()
    return chunks

def score(c: Chunk) -> Chunk:
    tl = c.text.lower(); dur = c.duration; pts = 70; reasons = ["High-retention speech hook"]; hook = Hook.GENERAL
    if not (5 <= dur <= 90):
        c.score = 0; c.viable = False; return c

    T1 = [(r"nobody (talks about|tells you)", Hook.SECRET, 25), (r"the (real|hidden) truth", Hook.REVELATION, 23)]
    for pat, h, p in T1:
        if re.search(pat, tl): pts += p; hook = h; reasons.append(f"Strong hook - {h.value}"); break

    c.score = min(99, max(50, pts)); c.hook = hook.value; c.reasons = reasons; c.viable = True
    return c

def select(scored: List[Chunk], n: int) -> List[Chunk]:
    pool = sorted([c for c in scored if c.viable], key=lambda x: -x.score)
    if not pool: pool = sorted(scored, key=lambda x: -x.score)
    sel: List[Chunk] = []; used: List[tuple] = []
    for c in pool:
        if len(sel) >= n: break
        # Avoid duplicate overlapping clips while allowing adjacent requested clips.
        if any(max(c.start, s) < min(c.end, e) for s, e in used): continue
        sel.append(c); used.append((c.start, c.end))
    sel.sort(key=lambda x: x.start)
    return sel

def fill_requested_chunks(chosen: List[Tuple[Chunk, str]], video_path: str, n: int, candidates: List[Chunk] = None) -> List[Tuple[Chunk, str]]:
    if len(chosen) >= n:
        return chosen[:n]
    existing = [(c.start, c.end) for c, _ in chosen]
    fallback_pool = candidates or build_uniform_chunks(video_path, n)
    for fallback in fallback_pool:
        if len(chosen) >= n:
            break
        overlaps = any(max(fallback.start, s) < min(fallback.end, e) for s, e in existing)
        if overlaps:
            continue
        chosen.append((fallback, fallback.title()))
        existing.append((fallback.start, fallback.end))
    if len(chosen) < n:
        logger.warning(f"Requested {n} clips but only {len(chosen)} non-overlapping clips could be selected.")
    return chosen

def generate_ass_file(words: List[dict], clip_start_sec: float, ass_out_path: str):
    """Generates an ASS subtitle file with OpusClip/Vizard clean typography and neon green active word highlighting"""
    header = """[Script Info]
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,42,&H00FFFFFF,&H0000FF00,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,1,2,50,50,140,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    lines_events = []
    clip_words = [w for w in words if (w.get("startMs", 0)/1000.0) >= clip_start_sec - 0.5]

    def format_time(sec):
        sec = max(0.0, sec)
        hrs = int(sec // 3600)
        mins = int((sec % 3600) // 60)
        secs = int(sec % 60)
        cs = int((sec % 1) * 100)
        return f"{hrs}:{mins:02d}:{secs:02d}.{cs:02d}"

    def ass_escape(text: str) -> str:
        return (
            text.replace("\\", "\\\\")
            .replace("{", "")
            .replace("}", "")
            .replace("\n", " ")
            .strip()
        )

    chunk_size = 3
    for i in range(0, len(clip_words), chunk_size):
        group = clip_words[i:i + chunk_size]
        if not group: continue

        for idx, active_w in enumerate(group):
            w_start = max(0.0, (active_w["startMs"] / 1000.0) - clip_start_sec)
            w_end = max(w_start + 0.25, (active_w["endMs"] / 1000.0) - clip_start_sec)

            formatted_words = []
            for j, w in enumerate(group):
                word_str = ass_escape(str(w.get("word", ""))).upper()
                if not word_str:
                    continue
                if j == idx:
                    formatted_words.append(f"{{\\c&H0000FF00&}}{word_str}{{\\r}}")
                else:
                    formatted_words.append(f"{{\\c&H00FFFFFF&}}{word_str}")

            line_text = " ".join(formatted_words)
            start_str = format_time(w_start)
            end_str = format_time(w_end)
            event_line = f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{line_text}"
            lines_events.append(event_line)

    with open(ass_out_path, "w", encoding="utf-8") as f:
        f.write(header + "\n".join(lines_events))

# ============================================================================
# TIER 3: DELIVERY LAYER (FFmpeg OpenCV Face-Tracking Crop & Supabase)
# ============================================================================
def analyze_face_centers(vpath: str, start_sec: float, end_sec: float, sample_fps: float = 2.0) -> list:
    """Track the most likely active speaker face center for dynamic 9:16 crops."""
    try:
        import cv2
        import numpy as np
        if not os.path.exists(vpath): return []
        cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        if not os.path.exists(cascade_path): return []

        face_cascade = cv2.CascadeClassifier(cascade_path)
        cap = cv2.VideoCapture(vpath)
        if not cap.isOpened(): return []

        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        width = cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 1920.0

        start_frame = int(start_sec * fps)
        end_frame = int(end_sec * fps)
        frame_step = max(1, int(fps / sample_fps))

        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)
        current_frame = start_frame
        points = []
        prev_gray = None
        tracked_x = None

        while current_frame <= end_frame:
            ret, frame = cap.read()
            if not ret: break
            t_rel = (current_frame - start_frame) / fps
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, minSize=(60, 60))
            if len(faces) > 0:
                frame_area = float(frame.shape[0] * frame.shape[1])
                best = None
                for x, y, w, h in faces:
                    center_x = (x + w / 2.0) / width
                    size_score = min(1.0, (w * h) / max(1.0, frame_area * 0.12))
                    center_score = 1.0 - min(1.0, abs(center_x - 0.5) * 2.0)
                    continuity_score = 1.0 - min(1.0, abs(center_x - tracked_x) * 3.0) if tracked_x is not None else center_score
                    motion_score = 0.0
                    if prev_gray is not None:
                        mouth_y1 = y + int(h * 0.55)
                        mouth_y2 = min(gray.shape[0], y + h)
                        mouth_x1 = max(0, x)
                        mouth_x2 = min(gray.shape[1], x + w)
                        curr_roi = gray[mouth_y1:mouth_y2, mouth_x1:mouth_x2]
                        prev_roi = prev_gray[mouth_y1:mouth_y2, mouth_x1:mouth_x2]
                        if curr_roi.size and prev_roi.shape == curr_roi.shape:
                            motion_score = min(1.0, float(np.mean(cv2.absdiff(curr_roi, prev_roi))) / 18.0)
                    score_val = (continuity_score * 0.45) + (motion_score * 0.30) + (center_score * 0.15) + (size_score * 0.10)
                    if best is None or score_val > best[0]:
                        best = (score_val, x, y, w, h)
                _, x, y, w, h = best
                center_x_norm = (x + w / 2.0) / width
                tracked_x = center_x_norm
                points.append((t_rel, center_x_norm))
            prev_gray = gray
            current_frame += frame_step
            cap.set(cv2.CAP_PROP_POS_FRAMES, current_frame)
        cap.release()
        return points
    except Exception as e:
        logger.warning(f"OpenCV face tracking error: {e}")
        return []

def build_dynamic_crop_x_expr(points: List[Tuple[float, float]]) -> str:
    """Build dynamic FFmpeg linear interpolation crop x expression from face points"""
    if not points: return "(in_w-out_w)/2"
    smoothed = []
    curr_bin = None
    bin_vals = []
    for t, x_norm in points:
        t_sec = int(t)
        if curr_bin is None: curr_bin = t_sec
        if t_sec == curr_bin:
            bin_vals.append(x_norm)
        else:
            smoothed.append((curr_bin, sum(bin_vals) / len(bin_vals)))
            curr_bin = t_sec
            bin_vals = [x_norm]
    if bin_vals and curr_bin is not None:
        smoothed.append((curr_bin, sum(bin_vals) / len(bin_vals)))
    if not smoothed: return "(in_w-out_w)/2"

    expr_parts = []
    for t_sec, norm_x in smoothed:
        target_x = f"min(max(0,in_w*{norm_x:.3f}-out_w/2),in_w-out_w)"
        expr_parts.append(f"gte(t,{t_sec:.1f}),{target_x}")

    expr = "(in_w-out_w)/2"
    for part in reversed(expr_parts):
        cond, val = part.split(",", 1)
        expr = f"if({cond},{val},{expr})"
    return expr

def transcode_and_upload(src: str, start: float, end: float, out: str, words: List[dict] = None, burn_captions: bool = False) -> str:
    """Safe FFmpeg crop + OpenCV Face-Tracking + ASS Kinetic Subtitles + Supabase CDN Upload"""
    dur = end - start

    # 1. Analyze face positions for dynamic 9:16 speaker tracking
    face_pts = analyze_face_centers(src, start, end)
    crop_x_expr = build_dynamic_crop_x_expr(face_pts)
    logger.info(f"OpenCV Face Tracking generated {len(face_pts)} face samples. Crop X expr: {crop_x_expr[:60]}...")

    # 2. Generate ASS Subtitle File if words provided
    ass_path = out + ".ass"
    use_subtitles = False
    if words and burn_captions:
        try:
            generate_ass_file(words, start, ass_path)
            use_subtitles = os.path.exists(ass_path)
        except Exception as e:
            logger.warning(f"ASS subtitle generation failed: {e}")

    crop_filter = f"scale=ih*9/16:ih:force_original_aspect_ratio=increase,crop=w=ih*9/16:h=ih:x='{crop_x_expr}':y=0,scale=720:1280"
    if use_subtitles:
        escaped_ass = ass_path.replace("\\", "/").replace(":", "\\:")
        vf = f"{crop_filter},subtitles='{escaped_ass}',fps=30"
    else:
        vf = f"{crop_filter},fps=30"

    def run_render(filter_graph: str, label: str):
        cmd = [
            resolve_media_binary("FFMPEG_BINARY", "ffmpeg"), "-y", "-hide_banner", "-loglevel", "error",
            "-ss", str(max(0.0, start - 1.5)), "-i", src, "-ss", str(min(1.5, start)), "-t", str(dur),
            "-vf", filter_graph, "-c:v", "libx264", "-preset", "ultrafast", "-crf", "26",
            "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", "-pix_fmt", "yuv420p", out
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise Exception(f"{label} FFmpeg transcode failed: {res.stderr[-300:] if res.stderr else 'Unknown error'}")
        validate_rendered_mp4(out, max(0.5, min(dur, 1.0)))

    try:
        run_render(vf, "Advanced")
    except Exception as primary_error:
        logger.warning(f"Advanced render failed; retrying basic fallback: {primary_error}")
        try:
            if os.path.exists(out):
                os.remove(out)
        except Exception:
            pass
        fallback_filter = "scale=ih*9/16:ih:force_original_aspect_ratio=increase,crop=w=ih*9/16:h=ih:x=(in_w-out_w)/2:y=0,scale=720:1280,fps=30"
        run_render(fallback_filter, "Fallback")

    if os.path.exists(ass_path):
        try: os.remove(ass_path)
        except: pass

    # Prefer Supabase Storage, but keep the locally generated Modal clip usable.
    fname = os.path.basename(out)
    if supabase:
        try:
            with open(out, 'rb') as f:
                res = supabase.storage.from_("clips").upload(path=fname, file=f, file_options={"content-type": "video/mp4", "upsert": "true"})
                logger.info(f"Supabase upload response: {res}")
            public_url = supabase.storage.from_("clips").get_public_url(fname)
            return public_url
        except Exception as e:
            logger.warning(f"Supabase clip upload failed; serving Modal clip locally: {e}")

    if modal_volume:
        try:
            modal_volume.commit()
        except Exception as ve:
            logger.warning(f"Modal volume commit note after clip transcode: {ve}")
    return f"/clips/{fname}"

def modal_inference_analyze_chunks(chunks: List[Chunk], n: int) -> List[dict]:
    """Call our private Qwen3.6-35B Modal Inference Endpoint"""
    from openai import OpenAI
    client = OpenAI(
        base_url="https://ibeekay1993--clipz-qwen.modal.run/v1",
        api_key="unauthenticated-endpoint" # Unauthenticated endpoint allows this
    )
    payload_chunks = [{"id": idx, "start": round(c.start, 1), "end": round(c.end, 1), "duration": round(c.duration, 1), "text": c.text} for idx, c in enumerate(chunks)]
    prompt = f"""
You are an elite viral video editor for TikTok, Instagram Reels, and YouTube Shorts.
Analyze these transcript chunks and select EXACTLY {n} viral clips. YOU MUST RETURN EXACTLY {n} CLIPS.
Choose segments that have high-retention hooks, emotional spikes, or contrarian opinions.

TRANSCRIPT CHUNKS:
{json.dumps(payload_chunks, indent=2)}

Return ONLY JSON: {{"clips": [{{"chunk_id": int, "title": str, "viralScore": int, "hookType": str, "viralReason": str}}]}}
"""
    try:
        resp = client.chat.completions.create(
            model="Qwen/Qwen3.6-35B-A3B",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        content = resp.choices[0].message.content
        if "```json" in content:
             content = content.split("```json")[1].split("```")[0].strip()
        data = json.loads(content)
        return data.get("clips", [])
    except Exception as e:
        logger.error(f"Modal Qwen3.6 Inference Error: {e}")
        return []

def deepseek_analyze_chunks(chunks: List[Chunk], n: int) -> List[dict]:
    """DeepSeek-R1 Viral Reasoning AI via Free OpenRouter Inference"""
    payload_chunks = [{"id": idx, "start": round(c.start, 1), "end": round(c.end, 1), "text": c.text} for idx, c in enumerate(chunks)]
    prompt = f"""
You are an elite viral video editor for TikTok, Instagram Reels, and YouTube Shorts.
Analyze the transcript chunks below and select EXACTLY {n} viral clips. YOU MUST RETURN EXACTLY {n} CLIPS.
Choose segments that have high-retention hooks, emotional spikes, or contrarian opinions.

TRANSCRIPT CHUNKS:
{json.dumps(payload_chunks, indent=2)}

Return ONLY JSON: {{"clips": [{{"chunk_id": int, "title": str, "viralScore": int, "hookType": str, "viralReason": str}}]}}
"""
    try:
        resp = requests.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={"Content-Type": "application/json"},
            json={"model": "deepseek/deepseek-r1:free", "messages": [{"role": "user", "content": prompt}]},
            timeout=10
        )
        if resp.status_code == 200:
            content = resp.json()['choices'][0]['message']['content']
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            return json.loads(content).get("clips", [])
    except Exception as e:
        logger.warning(f"DeepSeek-R1 reasoning skipped: {e}")
    return []

def gemini_analyze_chunks(chunks: List[Chunk], n: int) -> List[dict]:
    """Fallback Multi-Modal Virality Analysis via Google Gemini 2.0 / 2.5 Flash API"""
    gemini_key = os.getenv("GEMINI_API_KEY")
    if not gemini_key:
        return []

    payload_chunks = []
    for idx, c in enumerate(chunks):
        payload_chunks.append({
            "id": idx, "start": round(c.start, 1), "end": round(c.end, 1), "duration": round(c.duration, 1), "text": c.text
        })

    prompt = f"""
You are an elite viral video editor for TikTok, Instagram Reels, and YouTube Shorts (like OpusClip).
Analyze the following transcript chunks from a video and select EXACTLY {n} of the most engaging, high-retention segments. YOU MUST RETURN EXACTLY {n} CLIPS, NO MORE, NO LESS.
Choose segments that have high-retention hooks, emotional spikes, or contrarian opinions.

TRANSCRIPT CHUNKS:
{json.dumps(payload_chunks, indent=2)}

Return ONLY a JSON object with key "clips". Each clip must have:
- "chunk_id": int (the id of the selected chunk)
- "title": str (catchy headline with emoji, max 6 words)
- "viralScore": int (82 to 99)
- "hookType": str (one of: Secret, Revelation, Story, Contrarian, Tutorial, Curiosity, Emotional, Warning)
- "viralReason": str (1 crisp sentence explaining why this clip will perform well)
- "brollQuery": str (A highly visual search query for a background image/video that perfectly matches the context of the speech. e.g. "falling money", "dark hacker room", "peaceful forest")
"""
    try:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={gemini_key}"
        headers = {"Content-Type": "application/json"}
        data = {"contents": [{"parts": [{"text": prompt}]}], "generationConfig": {"response_mime_type": "application/json"}}
        resp = requests.post(url, headers=headers, json=data, timeout=12)
        if resp.status_code == 200:
            text_out = resp.json()['candidates'][0]['content']['parts'][0]['text']
            parsed = json.loads(text_out)
            return parsed.get("clips", [])
        else:
            logger.warning(f"Gemini Flash analysis status {resp.status_code}: {resp.text}")
            return []
    except Exception as e:
        logger.error(f"Gemini Flash analysis error: {e}")
        return []

def llama_analyze_chunks(chunks: List[Chunk], n: int) -> List[dict]:
    """Call Groq Llama-3-70B to score clips and write catchy viral headlines"""
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    payload_chunks = [{"id": idx, "start": round(c.start, 1), "end": round(c.end, 1), "duration": round(c.duration, 1), "text": c.text} for idx, c in enumerate(chunks)]
    prompt = f"""
You are an elite viral video editor for TikTok, Instagram Reels, and YouTube Shorts.
Analyze these transcript chunks and select EXACTLY {n} viral clips. YOU MUST RETURN EXACTLY {n} CLIPS.
Choose segments that have high-retention hooks, emotional spikes, or contrarian opinions.

TRANSCRIPT CHUNKS:
{json.dumps(payload_chunks, indent=2)}

Return ONLY JSON: {{"clips": [{{"chunk_id": int, "title": str, "viralScore": int, "hookType": str, "viralReason": str}}]}}
"""
    try:
        resp = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        data = json.loads(resp.choices[0].message.content)
        return data.get("clips", [])
    except Exception as e:
        logger.error(f"Groq Llama-3 analysis error: {e}")
        return []

def orchestrate_multi_ai_pipeline(chunks: List[Chunk], n: int) -> List[dict]:
    """
    Industry Best Practice: Dedicated Managed Inference Architecture
    - Groq Whisper-v3 -> Audio Speech-to-Text
    - Modal Qwen3.6-35B -> Dedicated Private GPU Inference (Zero Latency)
    - DeepSeek-R1 -> Deep Reasoning Fallback
    - Llama-3 -> Quick Virality Analysis Fallback
    - Gemini 2.0 -> Visual Intelligence Fallback
    """
    logger.info("Calling Private Modal Qwen3.6 Inference Endpoint...")
    clips = modal_inference_analyze_chunks(chunks, n)

    if not clips:
        logger.info("Delegating to DeepSeek-R1...")
        clips = deepseek_analyze_chunks(chunks, n)

    if not clips:
        logger.info("Delegating to Groq Llama-3...")
        clips = llama_analyze_chunks(chunks, n)

    if not clips:
        logger.info("Delegating to Google Gemini 2.0 Flash...")
        clips = gemini_analyze_chunks(chunks, n)

    return clips or []

# Persistent Job Tracking
JOBS = {}
modal_background_job_fn = None
modal_volume = None

STORAGE_DIR = _STORAGE_ROOT if _STORAGE_ROOT else ("/root/storage" if os.path.exists("/root/storage") or os.path.exists("/root") else tempfile.gettempdir())
JOBS_FILE = os.path.join(STORAGE_DIR, "jobs_state.json")

def _save_jobs_to_disk():
    try:
        os.makedirs(STORAGE_DIR, exist_ok=True)
        with open(JOBS_FILE, "w", encoding="utf-8") as f:
            json.dump(JOBS, f)
        if modal_volume:
            try:
                modal_volume.commit()
            except Exception as ve:
                logger.warning(f"Modal volume commit note: {ve}")
    except Exception as e:
        logger.warning(f"Could not persist jobs to disk: {e}")

def _load_jobs_from_disk():
    global JOBS
    if modal_volume:
        try:
            modal_volume.reload()
        except Exception as ve:
            pass
    if os.path.exists(JOBS_FILE):
        try:
            with open(JOBS_FILE, "r", encoding="utf-8") as f:
                disk_jobs = json.load(f)
                JOBS.update(disk_jobs)
        except Exception as e:
            logger.warning(f"Could not load jobs from disk: {e}")

def push_job_update(job_id: str, progress: int, current_step: str, status: str = None, result: dict = None, error: str = None):
    _load_jobs_from_disk()
    data = {
        "job_id": job_id,
        "progress": progress,
        "current_step": current_step
    }
    if status: data["status"] = status
    if result: data["result"] = result
    if error: data["error"] = error

    if job_id:
        if job_id not in JOBS:
            JOBS[job_id] = {"job_id": job_id, "status": "processing", "progress": 0, "current_step": "", "result": None, "error": None}
        JOBS[job_id].update(data)
        _save_jobs_to_disk()

    if supabase and job_id:
        try:
            supabase.table("jobs").upsert(data).execute()
        except Exception as e:
            logger.warning(f"Failed to persist job status in Supabase Postgres ({job_id}): {e}")

async def run_pipeline(vpath: str, url_or_name: str, n: int, base: str, job_id: str = None, burn_captions: bool = True) -> dict:
    def update_job(prog: int, step: str):
        if job_id:
            push_job_update(job_id, prog, step)

    update_job(10, "Extracting audio & speech transcription...")
    logger.info("Starting Multi-AI Engine transcript analysis...")
    words = []

    # Fast-Track 1: Try YoutubeTranscriptApi for YouTube links
    if "youtube.com" in url_or_name or "youtu.be" in url_or_name:
        try:
            vid_match = re.search(r'(?:v=|\/)([0-9A-Za-z_-]{11})', url_or_name)
            if vid_match:
                v_id = vid_match.group(1)
                from youtube_transcript_api import YouTubeTranscriptApi
                api = YouTubeTranscriptApi()
                yt_trans = api.fetch(v_id)
                if yt_trans:
                    logger.info(f"YouTubeTranscriptApi fast-track fetched {len(yt_trans)} captions for {v_id}")
                    for item in yt_trans:
                        s_ms = int(item.get('start', 0) * 1000)
                        d_ms = int(item.get('duration', 2.0) * 1000)
                        text_val = item.get('text', '')
                        for w in text_val.split():
                            words.append({"word": w, "startMs": s_ms, "endMs": s_ms + d_ms})
        except Exception as yte:
            logger.warning(f"YouTubeTranscriptApi fast-track note: {yte}")

    if not words:
        try:
            words = transcribe(vpath)
        except Exception as te:
            logger.warning(f"Speech transcription unavailable, falling back to timed clips: {te}")
            words = []

    chunks = semantic_chunks(words) if words else []
    if not chunks:
        logger.info("Generating fail-safe timed chunks...")
        chunks = build_uniform_chunks(vpath, n)
    if not chunks: raise HTTPException(500, "Could not form video segments")

    # Call Orchestrated Multi-AI Microservices Pipeline
    try:
        ai_analysis = orchestrate_multi_ai_pipeline(chunks, n)
    except Exception as ae:
        logger.warning(f"AI clip analysis unavailable, using heuristic chunk scores: {ae}")
        ai_analysis = []
    chosen_chunks = []
    if ai_analysis:
        for la in ai_analysis:
            cid = la.get("chunk_id", 0)
            if 0 <= cid < len(chunks):
                c = chunks[cid]
                c.score = la.get("viralScore", 85)
                c.hook = la.get("hookType", "General")
                c.reasons = [la.get("viralReason", "High-engagement viral hook")]
                c.broll_query = la.get("brollQuery", "")
                c.text = la.get("title", c.title()) # Override title
                chosen_chunks.append((c, la.get("title", c.title())))

    if len(chosen_chunks) < n:
        scored = [score(c) for c in chunks]
        heuristic_chosen = [(c, c.title()) for c in select(scored, n)]
        for hc, htitle in heuristic_chosen:
            if len(chosen_chunks) >= n:
                break
            if not any(cc[0].text == hc.text for cc in chosen_chunks):
                chosen_chunks.append((hc, htitle))

    chosen_chunks = fill_requested_chunks(chosen_chunks, vpath, n)

    update_job(55, "Rendering downloadable MP4 clips...")
    clips_out = [None] * len(chosen_chunks)

    def process_selected_chunk(index_and_tuple):
        i, (chunk, title_text) = index_and_tuple
        fname = f"clip_{uuid.uuid4().hex[:8]}_{i}.mp4"
        fpath = os.path.join(CLIPS_DIR, fname)
        try:
            clip_url = transcode_and_upload(vpath, chunk.start, chunk.end, fpath, words=chunk.words, burn_captions=burn_captions)
            if clip_url.startswith("/clips/"):
                clip_url = f"{base}{clip_url}"

            off = chunk.words[0]["startMs"] if chunk.words else int(chunk.start * 1000)
            captions = [{"word": w["word"], "startMs": w["startMs"] - off, "endMs": w["endMs"] - off} for w in chunk.words]
            return i, {
                "id": i,
                "title": title_text,
                "startSec": int(chunk.start),
                "endSec": int(chunk.end),
                "viralScore": chunk.score or 85,
                "viralReason": chunk.reasons[0] if chunk.reasons else "High-engagement clip",
                "captions": captions,
                "hookType": chunk.hook,
                "durationSec": round(chunk.duration, 1),
                "clipUrl": clip_url,
                "clip_url": clip_url,
                "brollQuery": getattr(chunk, "broll_query", ""),
            }
        except Exception as e:
            logger.error(f"Failed to render selected chunk {i}: {e}")
            return i, None

    with concurrent.futures.ThreadPoolExecutor(max_workers=render_worker_count(len(chosen_chunks))) as executor:
        futures = [executor.submit(process_selected_chunk, item) for item in enumerate(chosen_chunks)]
        for future in concurrent.futures.as_completed(futures):
            idx, rendered = future.result()
            if rendered:
                clips_out[idx] = rendered
                update_job(60 + int(((idx + 1) / max(1, len(chosen_chunks))) * 35), f"Rendered clip {idx + 1} of {len(chosen_chunks)}...")

    clips_out = [c for c in clips_out if c is not None]
    if not clips_out:
        raise Exception("No clips could be rendered into MP4 output.")

    if modal_volume:
        try:
            modal_volume.commit()
            logger.info("Committed modal_volume after all clips transcoded in run_pipeline.")
        except Exception as ve:
            logger.warning(f"Modal volume commit note in run_pipeline: {ve}")

    result = {"url": url_or_name, "duration": words[-1]["endMs"]/1000 if words else get_duration(vpath), "clips": clips_out, "status": "completed"}
    logger.info(f"Pipeline completed successfully. Rendered {len(clips_out)} clips.")
    update_job(100, "Complete")
    return result

async def run_youtube_transcript_first_pipeline(url: str, n: int, base: str, job_id: str = None) -> dict:
    """Fast path for captioned YouTube videos: score captions first, then download only selected windows."""
    def update_job(prog: int, step: str):
        if job_id:
            push_job_update(job_id, prog, step)

    update_job(8, "Fetching YouTube captions before downloading media...")
    words = fetch_youtube_transcript_words(url)
    if not words:
        raise Exception("No YouTube captions were available for transcript-first processing.")

    chunks = semantic_chunks(words)
    if not chunks:
        duration = max(30.0, words[-1]["endMs"] / 1000.0)
        chunks = []
        clip_count = max(1, min(n, 8))
        clip_len = min(35.0, max(12.0, duration / clip_count))
        for i in range(clip_count):
            start = i * clip_len
            end = min(start + clip_len, duration)
            clip_words = [w for w in words if start <= (w.get("startMs", 0) / 1000.0) <= end]
            if not clip_words:
                continue
            text = " ".join(w["word"] for w in clip_words)
            chunks.append(Chunk(start=start, end=end, text=text, words=clip_words, score=80, viable=True))
    if not chunks:
        raise Exception("Could not form caption-based clip segments.")

    update_job(18, "Scoring caption segments for viral moments...")
    try:
        ai_analysis = orchestrate_multi_ai_pipeline(chunks, n)
    except Exception as ae:
        logger.warning(f"Caption-first AI clip analysis unavailable, using heuristic scoring: {ae}")
        ai_analysis = []

    chosen_chunks = []
    if ai_analysis:
        for la in ai_analysis:
            cid = la.get("chunk_id", 0)
            if 0 <= cid < len(chunks):
                c = chunks[cid]
                c.score = la.get("viralScore", 85)
                c.hook = la.get("hookType", "General")
                c.reasons = [la.get("viralReason", "High-engagement viral hook")]
                c.broll_query = la.get("brollQuery", "")
                chosen_chunks.append((c, la.get("title", c.title())))

    if len(chosen_chunks) < n:
        scored = [score(c) for c in chunks]
        heuristic_chosen = [(c, c.title()) for c in select(scored, n)]
        for hc, htitle in heuristic_chosen:
            if len(chosen_chunks) >= n:
                break
            if not any(cc[0].text == hc.text for cc in chosen_chunks):
                chosen_chunks.append((hc, htitle))

    chosen_chunks = fill_requested_chunks(chosen_chunks, "", n, candidates=chunks)

    if not chosen_chunks:
        raise Exception("No viable caption segments selected.")

    clips_out = [None] * len(chosen_chunks)

    def process_youtube_clip(i, chunk, title_text):
        section_start = max(0.0, chunk.start - 2.0)
        section_end = chunk.end + 2.0
        section_path = download_youtube_section(url, RAW_UPLOADS_DIR, section_start, section_end, i, job_id)

        adjusted_words = []
        for w in chunk.words:
            adjusted_words.append({
                "word": w["word"],
                "startMs": max(0, int(w["startMs"] - (section_start * 1000))),
                "endMs": max(80, int(w["endMs"] - (section_start * 1000))),
            })

    update_job(50, "Analysis Complete. Awaiting User Edits...")
    clips_out = []
    for i, (chunk, title_text) in enumerate(chosen_chunks):
        off = chunk.words[0]["startMs"] if chunk.words else 0
        captions = [{"word": w["word"], "startMs": w["startMs"] - off, "endMs": w["endMs"] - off} for w in chunk.words]
        clips_out.append({
            "id": i,
            "title": title_text,
            "startSec": int(chunk.start),
            "endSec": int(chunk.end),
            "viralScore": chunk.score or 85,
            "viralReason": chunk.reasons[0] if chunk.reasons else "High-engagement caption segment",
            "captions": captions,
            "hookType": chunk.hook,
            "durationSec": round(chunk.duration, 1),
            "vpath": url # Since it's a URL, we pass the URL so the render job knows to download the section
        })

    clips_out = [c for c in clips_out if c is not None]

    return {"url": url, "duration": words[-1]["endMs"] / 1000.0 if words else 0, "clips": clips_out, "status": "needs_review"}


def execute_url_job_bg(job_id: str, url: str, n: int, base: str):
    try:
        if is_youtube_url(url):
            try:
                import asyncio
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                res = loop.run_until_complete(run_youtube_transcript_first_pipeline(url, n, base, job_id))
                push_job_update(job_id, progress=100, current_step="Complete", status="completed", result=res)
                return
            except Exception as fast_err:
                logger.warning(f"Transcript-first YouTube pipeline failed; trying bounded section fallback: {fast_err}")
                push_job_update(job_id, progress=6, current_step="YouTube captions are blocked; trying a short media section instead...")

            try:
                section_path = download_youtube_section(url, RAW_UPLOADS_DIR, 0.0, 90.0, 0, job_id)
                execute_job_bg(job_id, section_path, url, n, base)
                return
            except Exception as section_err:
                logger.warning(f"Bounded YouTube section fallback failed: {section_err}")
                if os.getenv("RAPIDAPI_KEY"):
                    push_job_update(job_id, progress=8, current_step="Using configured YouTube ingestion provider...")
                    vpath = download_video_ingest(url, RAW_UPLOADS_DIR, job_id)
                    execute_job_bg(job_id, vpath, url, n, base)
                    return
                raise Exception("YouTube link import is not configured for this cloud server. Upload the video file directly to generate clips reliably.")

        vpath = download_video_ingest(url, RAW_UPLOADS_DIR, job_id)
        execute_job_bg(job_id, vpath, url, n, base)
    except Exception as e:
        logger.error(f"URL job {job_id} failed: {e}")
        push_job_update(job_id, progress=0, current_step="Failed", status="failed", error=str(e))

def execute_render_job_bg(job_id: str, url: str, clips: List[dict], base: str):
    try:
        import asyncio
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

        is_yt = is_youtube_url(url)
        vpath = url if is_yt else url

        def update_job(prog: int, step: str):
            push_job_update(job_id, prog, step)

        update_job(60, "FFmpeg 1080p HD Safe Crop & Subtitle Transcoding...")
        clips_out = [None] * len(clips)

        def process_clip(i, clip):
            fname = f"clip_{uuid.uuid4().hex[:8]}_{i}.mp4"
            fpath = os.path.join(CLIPS_DIR, fname)
            try:
                if is_yt:
                    section_start = max(0.0, float(clip['startSec']) - 2.0)
                    section_end = float(clip['endSec']) + 2.0
                    sec_path = download_youtube_section(url, RAW_UPLOADS_DIR, section_start, section_end, i)
                    adj_start = float(clip['startSec']) - section_start
                    adj_end = float(clip['endSec']) - section_start

                    w_adjusted = []
                    for w in clip['captions']:
                        w_copy = w.copy()
                        w_copy["startMs"] = w["startMs"]
                        w_copy["endMs"] = w["endMs"]
                        w_adjusted.append(w_copy)

                    clip_url = transcode_and_upload(sec_path, adj_start, adj_end, fpath, words=w_adjusted, burn_captions=True)
                else:
                    clip_url = transcode_and_upload(vpath, float(clip['startSec']), float(clip['endSec']), fpath, words=clip['captions'], burn_captions=True)

                if clip_url.startswith("/clips/"):
                    clip_url = f"{base}{clip_url}"
                clip['clip_url'] = clip_url
                clip['clipUrl'] = clip_url
                return i, clip
            except Exception as e:
                logger.error(f"Failed to transcode chunk {i}: {e}")
                return i, None

        with concurrent.futures.ThreadPoolExecutor(max_workers=render_worker_count(len(clips))) as executor:
            futures = {executor.submit(process_clip, i, c): i for i, c in enumerate(clips)}
            for future in concurrent.futures.as_completed(futures):
                idx, res_data = future.result()
                if res_data:
                    clips_out[idx] = res_data

        clips_out = [c for c in clips_out if c is not None]
        if not clips_out:
            raise Exception("No clips could be rendered into MP4 output.")

        if modal_volume:
            try:
                modal_volume.commit()
                logger.info("Committed modal_volume after all clips transcoded.")
            except Exception as ve:
                logger.warning(f"Modal volume commit note in render job: {ve}")

        res = {"url": url, "duration": 0, "clips": clips_out, "status": "completed"}
        push_job_update(job_id, progress=100, current_step="Complete", status="completed", result=res)
    except Exception as e:
        logger.error(f"Render job {job_id} failed: {e}")
        push_job_update(job_id, progress=0, current_step="Failed", status="failed", error=str(e))

def execute_job_bg(job_id: str, vpath: str, url_or_name: str, n: int, base: str):
    try:
        import asyncio
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        res = loop.run_until_complete(run_pipeline(vpath, url_or_name, n, base, job_id))
        push_job_update(job_id, progress=100, current_step="Complete", status="completed", result=res)
    except Exception as e:
        logger.error(f"Job {job_id} failed: {e}")
        push_job_update(job_id, progress=0, current_step="Failed", status="failed", error=str(e))

@app.post("/api/process")
async def process_video_api(body: ProcessRequest, request: Request):
    if not body.url.strip(): raise HTTPException(400, "URL cannot be empty")
    base = str(request.base_url).rstrip("/")
    try:
        vpath = await run_in_threadpool(download_video_ingest, body.url.strip(), RAW_UPLOADS_DIR)
        return await run_pipeline(vpath, body.url.strip(), max(1, min(body.num_clips, 8)), base, burn_captions=body.burn_captions)
    except Exception as e:
        logger.error(f"Process failed: {e}")
        raise HTTPException(500, str(e))

run_background_job_modal = None
run_background_upload_job_modal = None
run_background_render_job_modal = None

@app.post("/api/jobs/render")
async def create_render_job_api(body: RenderRequest, background_tasks: BackgroundTasks, request: Request = None):
    if not body.clips: raise HTTPException(400, "Clips cannot be empty")
    base = str(request.base_url).rstrip("/") if request else "https://ibeekay1993--clipz-stream-fastapi-app.modal.run"
    job_id = uuid.uuid4().hex[:12]

    push_job_update(
        job_id=job_id,
        progress=50,
        current_step="Applying your edits and rendering 1080p clips...",
        status="processing"
    )

    background_tasks.add_task(execute_render_job_bg, job_id, body.url, body.clips, base)
    logger.info(f"Queued render background task for job {job_id}")

    return {"job_id": job_id, "status": "processing"}

@app.post("/api/jobs/create")
async def create_job_api(body: ProcessRequest, background_tasks: BackgroundTasks, request: Request = None):
    if not body.url.strip(): raise HTTPException(400, "URL cannot be empty")
    base = str(request.base_url).rstrip("/") if request else "https://ibeekay1993--clipz-stream-fastapi-app.modal.run"
    job_id = uuid.uuid4().hex[:12]

    push_job_update(
        job_id=job_id,
        progress=2,
        current_step="Ingesting video & validating media streams...",
        status="processing"
    )

    num_c = max(1, min(body.num_clips, 8))

    background_tasks.add_task(execute_url_job_bg, job_id, body.url.strip(), num_c, base)
    logger.info(f"Queued URL background task for job {job_id}")

    return {"job_id": job_id, "status": "processing"}

@app.get("/api/jobs/status/{job_id}")
async def get_job_status(job_id: str):
    _load_jobs_from_disk()
    if job_id in JOBS:
        return JOBS[job_id]

    if supabase:
        try:
            res = supabase.table("jobs").select("*").eq("job_id", job_id).execute()
            if res.data and len(res.data) > 0:
                return res.data[0]
        except Exception as e:
            logger.warning(f"Failed to fetch job status from Supabase DB ({job_id}): {e}")

    raise HTTPException(404, "Job not found")

@app.post("/api/upload")
async def upload_video_api(request: Request, background_tasks: BackgroundTasks, file: UploadFile = File(...), num_clips: int = Form(3)):
    base = str(request.base_url).rstrip("/")
    ext = os.path.splitext(file.filename)[1] or ".mp4"
    job_id = uuid.uuid4().hex[:12]
    vpath = os.path.join(RAW_UPLOADS_DIR, f"uploaded_{job_id}{ext}")
    try:
        with open(vpath, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        push_job_update(
            job_id=job_id,
            progress=5,
            current_step="File uploaded successfully. Preparing AI pipeline...",
            status="processing"
        )

        num_c = max(1, min(num_clips, 8))

        background_tasks.add_task(execute_job_bg, job_id, vpath, file.filename, num_c, base)
        logger.info(f"Queued uploaded file background task for job {job_id}")

        return {"job_id": job_id, "status": "processing"}
    except Exception as e:
        logger.error(f"Upload failed: {e}")
        raise HTTPException(500, str(e))

@app.get("/clips/{filename}")
async def serve_clip(filename: str):
    if modal_volume:
        try:
            modal_volume.reload()
        except Exception as ve:
            logger.warning(f"Modal volume reload note before serving clip: {ve}")
    path = os.path.join(CLIPS_DIR, filename)
    if not os.path.exists(path):
        raise HTTPException(404, "Clip not found")
    return FileResponse(path, media_type="video/mp4")

@app.get("/api/capabilities")
async def capabilities():
    cookie_file = os.getenv("YTDLP_COOKIES_FILE")
    has_cookie_file = bool(cookie_file and os.path.exists(cookie_file))
    youtube_configured = bool(os.getenv("RAPIDAPI_KEY") or os.getenv("YTDLP_COOKIES_CONTENT") or os.getenv("YTDLP_PROXY") or has_cookie_file)
    return {
        "upload_enabled": True,
        "youtube_link_import_enabled": youtube_configured,
        "youtube_message": "YouTube link import needs a configured ingestion provider. Upload MP4 files for the most reliable clipping."
    }
@app.get("/health")
def health():
    return {"status": "ok", "architecture": "Groq Llama-3-70B + Supabase Serverless"}

@app.get("/")
def root():
    return {"api": "POST /api/process, POST /api/jobs/create, GET /api/jobs/status/{job_id}", "health": "GET /health"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8000)))

# Modal Cloud Deployment Handler
try:
    import modal
    image = (
        modal.Image.debian_slim(python_version="3.11")
        .pip_install("fastapi", "yt-dlp>=2025.07.21", "groq", "requests", "supabase", "python-dotenv", "python-multipart", "opencv-python-headless", "youtube-transcript-api")
        .apt_install("ffmpeg")
    )
    modal_app = modal.App("clipz-stream")

    # Load secrets directly from Modal Cloud (configured in Modal Dashboard)
    secret = modal.Secret.from_name("clipz-secrets")
    secrets_list = [secret]

    # Attach the shared Modal Volume so state is preserved across container replicas
    modal_volume_instance = modal.Volume.from_name("clipz-shared-storage", create_if_missing=True)
    modal_volume = modal_volume_instance  # bind to global

    @modal_app.function(
        image=image,
        timeout=600,
        cpu=2.0,
        secrets=secrets_list,
        volumes={"/root/storage": modal_volume_instance}
    )
    def run_background_job_modal(job_id: str, url: str, num_clips: int, base_url: str):
        execute_url_job_bg(job_id, url, num_clips, base_url)

    @modal_app.function(
        image=image,
        timeout=600,
        cpu=2.0,
        secrets=secrets_list,
        volumes={"/root/storage": modal_volume_instance}
    )
    def run_background_upload_job_modal(job_id: str, vpath: str, filename: str, num_clips: int, base_url: str):
        execute_job_bg(job_id, vpath, filename, num_clips, base_url)

    @modal_app.function(
        image=image,
        timeout=600,
        cpu=2.0,
        secrets=secrets_list,
        volumes={"/root/storage": modal_volume_instance}
    )
    def run_background_render_job_modal(job_id: str, url: str, clips: list, base_url: str):
        execute_render_job_bg(job_id, url, clips, base_url)

    @modal_app.function(
        image=image,
        timeout=600,
        cpu=2.0,
        secrets=secrets_list,
        volumes={"/root/storage": modal_volume_instance}
    )
    @modal.asgi_app()
    def fastapi_app():
        return app
except Exception as e:
    print(f"Modal init error: {e}")
    pass
